# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9e4bbe2b50c4fb5ee91efc64f993b382fa3ee18ba87d86b7e900b04ccf3e5bfef1a3d793cc9e7a23f77231c865cb759ce220e2eb9f63ba7814838ad5847a844

test:
  secret_key_base: ff171e8392cca76f743491898236a546de67f81ddc1bba2293468b09a8228c7693bda162c07c336c6166c76cc00b723e0363e85a5f277d5dde9f0ffd6a26000a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
